"""Legal disclaimers, system prompts, and constants.

Every piece of AI-generated text MUST carry the advisory disclaimer.
This is non-negotiable for legal compliance.
"""

# ---------------------------------------------------------------------------
# Legal / Disclaimer constants
# ---------------------------------------------------------------------------

ADVISORY_DISCLAIMER = (
    "IMPORTANT: This information is generated by an AI assistant and is "
    "provided for INFORMATIONAL and ADVISORY purposes only. It does NOT "
    "constitute professional emergency management, medical, legal, or "
    "travel advice. Always follow instructions from local authorities, "
    "official emergency services, and your country's embassy or consulate. "
    "The developers and operators of this service accept no liability for "
    "actions taken based on this information. When in doubt, call local "
    "emergency services immediately."
)

MEDICAL_DISCLAIMER = (
    "This service does not provide medical advice. If you or someone near "
    "you is injured, call local emergency services immediately."
)

DATA_FRESHNESS_WARNING = (
    "Information is based on data available at the time of generation and "
    "may not reflect the current situation. Conditions can change rapidly "
    "during emergencies."
)

# ---------------------------------------------------------------------------
# AI System Prompt — enforces advisory language
# ---------------------------------------------------------------------------

AI_SYSTEM_PROMPT = """\
You are an emergency advisory assistant for travelers. Your role is to help \
people understand emergency situations and consider their options.

CRITICAL RULES — you MUST follow these at all times:
1. NEVER use imperative/command language. Never say "go to", "do this", \
   "you must", "leave now". Instead use: "you may want to consider", \
   "it might be advisable to", "one option could be", "some travelers in \
   similar situations have".
2. ALWAYS recommend contacting local emergency services and official authorities.
3. NEVER give medical advice. If someone is injured, tell them to call \
   emergency services.
4. ALWAYS acknowledge uncertainty. Say "based on available information" or \
   "reports suggest" rather than stating things as absolute facts.
5. Keep responses concise — travelers may have limited connectivity.
6. Prioritize information by urgency: immediate safety first, then \
   evacuation options, then logistics.
7. Include the local emergency number for the relevant country when known.
8. NEVER guarantee safety of any route, location, or action.
9. If data is incomplete or stale, say so explicitly.

You will receive structured data about alerts, transport, and the user's \
location. Synthesize this into clear, prioritized, advisory guidance.\
"""

# ---------------------------------------------------------------------------
# Emergency severity levels
# ---------------------------------------------------------------------------

SEVERITY_LEVELS = {
    "critical": "Immediate threat to life. Seek shelter or evacuate per local authority guidance.",
    "high": "Significant risk. Monitor official channels and prepare to act.",
    "medium": "Elevated risk. Stay informed and review your options.",
    "low": "Minor disruption. Continue with caution and stay aware.",
    "info": "Informational. No immediate action suggested.",
}

# ---------------------------------------------------------------------------
# Supported emergency types
# ---------------------------------------------------------------------------

EMERGENCY_TYPES = [
    "earthquake",
    "flood",
    "wildfire",
    "tsunami",
    "hurricane",
    "tornado",
    "volcanic_eruption",
    "landslide",
    "geopolitical",
    "civil_unrest",
    "terrorism",
    "industrial_accident",
    "pandemic",
    "infrastructure_failure",
    "other",
]
