"""AI guidance models — every response MUST include advisory metadata."""

from datetime import datetime

from pydantic import BaseModel, Field

from .common import AdvisoryMeta, Location

__all__ = ["GuidanceRequest", "GuidanceResponse"]


class GuidanceRequest(BaseModel):
    """Request for AI-generated advisory guidance."""

    latitude: float = Field(..., ge=-90, le=90)
    longitude: float = Field(..., ge=-180, le=180)
    situation: str = Field(
        "",
        max_length=500,
        description="Optional: what the user is experiencing in their own words",
    )
    language: str = Field("en", description="Preferred language (ISO 639-1)")


class GuidanceResponse(BaseModel):
    """AI-generated advisory guidance.

    The `advisory_meta` field is MANDATORY and must always be populated.
    The `advisory_text` is generated by AI and framed as suggestions, never commands.
    """

    action_suggestion: str = Field(
        ...,
        description=(
            "High-level suggested action: 'consider_shelter' | 'consider_evacuation' | "
            "'monitor_situation' | 'no_immediate_concern'"
        ),
    )
    advisory_text: str = Field(
        ...,
        description="AI-generated advisory text (suggestions, NOT commands)",
    )
    priority_steps: list[str] = Field(
        default_factory=list,
        description="Prioritized list of suggested considerations",
    )
    local_emergency_number: str = Field(
        "",
        description="Local emergency number for the country (e.g. '112', '911')",
    )
    embassy_info: str = Field(
        "",
        description="Nearest embassy/consulate info if available",
    )
    location: Location = Field(..., description="Location this guidance is for")
    advisory_meta: AdvisoryMeta = Field(
        ...,
        description="MANDATORY: Legal disclaimers, data sources, confidence score",
    )
    generated_at: datetime = Field(..., description="Timestamp of generation (UTC)")
